language: php

php:
  - 5.3
  - 5.6
  - hhvm

sudo: false

before_script:
  - composer install --prefer-source

install:
  - travis_retry composer install --prefer-source

script:
  - composer ci

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover