language: php

php:
  - 5.3
  - 5.6
  - hhvm

services:
  - mongodb

before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --prefer-source

install:
  - travis_retry composer install --prefer-source

script:
  - composer ci

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
